stages:
  - build
  - deploy
  - cleanup

variables:
  PULUMI_SKIP_UPDATE_CHECK: true
  PULUMI_HOME: ${CI_PROJECT_DIR}/.pulumi
  AWS_REGION: "us-east-1"

image:
  name: registry.cn-hangzhou.aliyuncs.com/goldenimage/pulumi:3.35.3

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - node_modules/
    - .pulumi/
    - package-lock.json
  policy: pull

before_script:
  - cp /etc/gitlab-runner/certs/gitlab.home.local.crt /usr/local/share/ca-certificates/ca.crt
  - update-ca-certificates

build:
  stage: build
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - node_modules/
      - .pulumi/
      - package-lock.json
    policy: pull-push
  script:
    - pulumi login 's3://state?endpoint=minio.home.local:80&disableSSL=true&s3ForcePathStyle=true'
    - pulumi stack select k3s-it-prd-infra-shared-01/prometheus
    - pulumi plugin install resource kubernetes v3.30.2 --server https://obs.home.local/mirror/pulumi/plugins
    - pulumi plugin install resource random v4.16.7 --server https://obs.home.local/mirror/pulumi/plugins
    - npm config set registry https://registry.npmmirror.com
    - npm install

deploy:
  stage: deploy
  script:
    - git -c http.sslVerify=false clone https://gitea.home.local/suzhetao/pulumi-ts-module-kubernetes.git
    - pulumi up -yf
  rules:
    - if: $CI_COMMIT_TITLE == "deploy"
      when: on_success 

cleanup:
  stage: cleanup
  script:
    - git -c http.sslVerify=false clone https://gitea.home.local/suzhetao/pulumi-ts-module-kubernetes.git
    - pulumi destroy -yf
  rules:
    - if: $CI_COMMIT_TITLE == "destroy"
      when: on_success